### ISSUE TITLE
Create action throws an error if there is no primary read action

### ISSUE THREAD

**Issue by diogomrts** [ash-project/ash_json_api#248]
When trying to create a simple resource that handles a post request we get an error saying there is no primary read action, even though it is never called.

This is my example resource:

```elixir
defmodule App.Core.CallFeedback do
  use Ash.Resource,
    domain: App.Core,
    extensions: [AshJsonApi.Resource]

  require Logger

  json_api do
    type "call_feedback"
  end

  attributes do
    attribute :id, :string, primary_key?: true, allow_nil?: false
    attribute :contact_id, :string, allow_nil?: false, public?: true
    attribute :campaign_id, :string, public?: true
    attribute :user_id, :string, public?: true
  end

  actions do
    create :submit do
      primary? true
      accept [:*]

      manual fn changeset, context ->
        {:ok, Map.merge(changeset.data, changeset.attributes)}
      end
    end
  end
end
```

And the error it throws:

```elixir
15:04:11.987 [warning] `e6addf97-ebc8-443a-8c56-77ecbf2fa752`: AshJsonApi.Error not implemented for error:

** (Ash.Error.Invalid.NoPrimaryAction) No primary action of type :read for resource App.Core.CallFeedback, and no action specified
    (elixir 1.17.3) lib/process.ex:864: Process.info/2
    (ash 3.4.29) lib/ash/error/invalid/no_primary_action.ex:5: Ash.Error.Invalid.NoPrimaryAction.exception/1
    (ash 3.4.29) lib/ash/helpers.ex:262: Ash.Helpers.get_action/4
    (ash 3.4.29) lib/ash.ex:1853: Ash.load/3
    (ash 3.4.29) lib/ash.ex:1813: Ash.load/3
    (ash 3.4.29) lib/ash/actions/helpers.ex:582: Ash.Actions.Helpers.load/4
    (ash 3.4.29) lib/ash/actions/create/create.ex:467: Ash.Actions.Create.commit/3
    (ash 3.4.29) lib/ash/actions/create/create.ex:112: Ash.Actions.Create.do_run/4
    (ash 3.4.29) lib/ash/actions/create/create.ex:50: Ash.Actions.Create.run/4
    (ash_json_api 1.4.11) lib/ash_json_api/controllers/helpers.ex:273: anonymous fn/1 in AshJsonApi.Controllers.Helpers.create_record/1
    (ash_json_api 1.4.11) lib/ash_json_api/controllers/post.ex:20: AshJsonApi.Controllers.Post.call/2
    (console 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in App.Api.Json.dispatch/2
    (telemetry 1.3.0) /Users/diogomartins/Projects/console/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
    (console 0.1.0) deps/plug/lib/plug/router.ex:242: App.Api.Json.dispatch/2
    (console 0.1.0) lib/app/api/json.ex:1: App.Api.Json.plug_builder_call/2
    (phoenix 1.7.14) lib/phoenix/router/route.ex:42: Phoenix.Router.Route.call/2
    (phoenix 1.7.14) lib/phoenix/router.ex:484: Phoenix.Router.__call__/5
    (console 0.1.0) lib/console_web/endpoint.ex:1: ConsoleWeb.Endpoint.plug_builder_call/2
    (console 0.1.0) lib/console_web/endpoint.ex:1: ConsoleWeb.Endpoint."call (overridable 3)"/2
    (console 0.1.0) deps/plug/lib/plug/debugger.ex:136: ConsoleWeb.Endpoint."call (overridable 4)"/2
```

I added an action as a workaround but with a logger and can see that it is never really called:

```elixir
read :read do
  primary? true

  manual fn _ash_query, _opts, _context ->
    Logger.error("create expects a primary read action to be defined so we have this")
    {:error, "foo"}
  end
end
```

** Runtime
* Elixir & Erlang versions (elixir --version): Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:11:11] [ds:11:11:10] [async-threads:1] [jit]

Elixir 1.17.3 (compiled with Erlang/OTP 27)

* VSCode ElixirLS version: 0.24.2
* Operating System Version: darwin 23.6.0

**Comment by zachdaniel** [comment]
@diogomrts I've fixed this in Ash main if you want to give it a try. You can see the commit message for more, but there may still be some rough edges to sharpen.
