### ISSUE TITLE
undefined function routes/1

### ISSUE THREAD

**Issue by andrewcallahan** [ash-project/ash_json_api#26]
**Describe the bug**
```
== Compilation error in file lib/resources/behavior_plan_service.ex ==
** (CompileError) lib/resources/behavior_plan_service.ex:10: undefined function routes/1
    expanding macro: AshJsonApi.JsonApiResource.json_api/1
    lib/resources/behavior_plan_service.ex:6: Blueprint.BehaviorPlanService (module)
    (elixir 1.10.2) lib/kernel/parallel_compiler.ex:304: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

**To Reproduce**

I have a resource with a json_api block like this
```
  json_api do
    fields [:behavior_plan, :service]
    include [:behavior_plan, :service]

    routes do
      index :default, primary?: true
      get :default, primary?: true
      post :default
      patch :default
      delete :default

      relationship_read_routes :behavior_plan
      relationship_change_routes :behavior_plan

      relationship_read_routes :service
      relationship_change_routes :service
    end
  end
```
I then ran `iex -S mix phx.server`

**Expected behavior**
This should compile

** Runtime
 - Elixir version: 1.10.2
 - Erlang version: OTP/22
 - OS: Mac OS
 - Ash version: 0.3.0
 - any related extension versions: AshPostgres 0.1.4, AshJsonApi 0.1.5

**Additional context**
N/A

**Comment by zachdaniel** [comment]
This is a result of a change to the json_api syntax for declaring routes. It is now

```
routes "/behavior_plan_services" do
 ...
end
```

Don't forget to add `type` as well

```
json_api do
  type "behavior_plan_service"

  ...
end
```

**Comment by andrewcallahan** [comment]
👍
